import type {
  Book,
  BookPage,
  DamageArea,
  PaperCategory,
  PaperStock,
  Point,
  RestorationRecord,
} from '../types';

const dynasties = ['唐', '宋', '元', '明', '清', '现代'] as const;
const paperTypes = ['宣纸', '皮纸', '竹纸', '棉纸', '麻纸'] as const;
const subTypes = ['净皮', '棉料', '特净', '红星', '汪六吉', '普通', '上品'] as const;
const fiberCompositions = [
  '青檀皮',
  '青檀皮、沙田稻草',
  '楮皮',
  '桑皮',
  '竹纤维',
  '大麻',
  '苎麻',
  '棉纤维',
  '木浆',
  '竹浆',
];

function generateId(prefix: string, index: number): string {
  return `${prefix}_${index.toString().padStart(3, '0')}`;
}

export const mockPaperCategories: PaperCategory[] = (() => {
  const categories: PaperCategory[] = [];
  let id = 1;
  for (const dynasty of dynasties) {
    for (const paperType of paperTypes) {
      const subType = subTypes[Math.floor(Math.random() * subTypes.length)];
      categories.push({
        id: generateId('cat', id),
        dynasty,
        paperType,
        subType,
        description: `${dynasty}代${paperType}，${subType}品质，${dynasty === '现代' ? '采用传统工艺仿制' : '保存完好，具有历史价值'}`,
      });
      id++;
    }
  }
  return categories;
})();

export const mockPaperStock: PaperStock[] = [
  {
    id: 'paper_001',
    categoryId: 'cat_001',
    batchNumber: 'BATCH-2024-001',
    curtainPatternSpacing: 1.2,
    fiberComposition: '青檀皮、沙田稻草',
    thickness: 0.08,
    colorL: 85,
    colorA: 2,
    colorB: 12,
    pHValue: 7.2,
    stockQuantity: 100,
    unit: '张',
    storageLocation: 'A-01-01',
    purchaseDate: '2024-01-15',
    supplier: '安徽泾县宣纸厂',
    notes: '特级红星宣纸，适合修复唐代珍贵古籍',
  },
  {
    id: 'paper_002',
    categoryId: 'cat_002',
    batchNumber: 'BATCH-2024-002',
    curtainPatternSpacing: 1.5,
    fiberComposition: '楮皮',
    thickness: 0.06,
    colorL: 82,
    colorA: 3,
    colorB: 15,
    pHValue: 7.0,
    stockQuantity: 150,
    unit: '张',
    storageLocation: 'A-01-02',
    purchaseDate: '2024-02-20',
    supplier: '浙江富阳皮纸厂',
    notes: '唐代风格皮纸，纤维细长',
  },
  {
    id: 'paper_003',
    categoryId: 'cat_003',
    batchNumber: 'BATCH-2024-003',
    curtainPatternSpacing: 1.8,
    fiberComposition: '竹纤维',
    thickness: 0.05,
    colorL: 78,
    colorA: 1,
    colorB: 18,
    pHValue: 6.8,
    stockQuantity: 200,
    unit: '张',
    storageLocation: 'A-01-03',
    purchaseDate: '2024-03-10',
    supplier: '福建连城竹纸厂',
    notes: '唐代竹纸仿制，适合普通古籍修复',
  },
  {
    id: 'paper_004',
    categoryId: 'cat_006',
    batchNumber: 'BATCH-2024-004',
    curtainPatternSpacing: 1.3,
    fiberComposition: '青檀皮',
    thickness: 0.09,
    colorL: 88,
    colorA: 1,
    colorB: 10,
    pHValue: 7.5,
    stockQuantity: 80,
    unit: '张',
    storageLocation: 'A-02-01',
    purchaseDate: '2024-01-25',
    supplier: '安徽泾县红星宣纸厂',
    notes: '宋代风格净皮宣纸，厚度适中',
  },
  {
    id: 'paper_005',
    categoryId: 'cat_007',
    batchNumber: 'BATCH-2024-005',
    curtainPatternSpacing: 1.6,
    fiberComposition: '桑皮',
    thickness: 0.07,
    colorL: 80,
    colorA: 4,
    colorB: 14,
    pHValue: 7.1,
    stockQuantity: 120,
    unit: '张',
    storageLocation: 'A-02-02',
    purchaseDate: '2024-02-15',
    supplier: '山东临朐桑皮纸厂',
    notes: '宋代皮纸，质地坚韧',
  },
  {
    id: 'paper_006',
    categoryId: 'cat_008',
    batchNumber: 'BATCH-2024-006',
    curtainPatternSpacing: 2.0,
    fiberComposition: '竹纤维',
    thickness: 0.06,
    colorL: 75,
    colorA: 2,
    colorB: 20,
    pHValue: 6.5,
    stockQuantity: 180,
    unit: '张',
    storageLocation: 'A-02-03',
    purchaseDate: '2024-03-05',
    supplier: '江西铅山竹纸厂',
    notes: '宋代竹纸，帘纹清晰',
  },
  {
    id: 'paper_007',
    categoryId: 'cat_011',
    batchNumber: 'BATCH-2024-007',
    curtainPatternSpacing: 1.4,
    fiberComposition: '青檀皮、沙田稻草',
    thickness: 0.085,
    colorL: 86,
    colorA: 2,
    colorB: 11,
    pHValue: 7.3,
    stockQuantity: 90,
    unit: '张',
    storageLocation: 'A-03-01',
    purchaseDate: '2024-04-01',
    supplier: '安徽泾县汪六吉宣纸厂',
    notes: '元代风格棉料宣纸',
  },
  {
    id: 'paper_008',
    categoryId: 'cat_012',
    batchNumber: 'BATCH-2024-008',
    curtainPatternSpacing: 1.7,
    fiberComposition: '楮皮',
    thickness: 0.075,
    colorL: 79,
    colorA: 3,
    colorB: 16,
    pHValue: 6.9,
    stockQuantity: 110,
    unit: '张',
    storageLocation: 'A-03-02',
    purchaseDate: '2024-04-15',
    supplier: '浙江温州皮纸厂',
    notes: '元代皮纸，质地柔软',
  },
  {
    id: 'paper_009',
    categoryId: 'cat_013',
    batchNumber: 'BATCH-2024-009',
    curtainPatternSpacing: 1.9,
    fiberComposition: '竹浆',
    thickness: 0.055,
    colorL: 76,
    colorA: 1,
    colorB: 19,
    pHValue: 6.7,
    stockQuantity: 160,
    unit: '张',
    storageLocation: 'A-03-03',
    purchaseDate: '2024-04-20',
    supplier: '四川夹江竹纸厂',
    notes: '元代竹纸，适合量大修复',
  },
  {
    id: 'paper_010',
    categoryId: 'cat_016',
    batchNumber: 'BATCH-2024-010',
    curtainPatternSpacing: 1.25,
    fiberComposition: '青檀皮',
    thickness: 0.095,
    colorL: 87,
    colorA: 1,
    colorB: 9,
    pHValue: 7.4,
    stockQuantity: 70,
    unit: '张',
    storageLocation: 'B-01-01',
    purchaseDate: '2024-05-01',
    supplier: '安徽泾县红星宣纸厂',
    notes: '明代特净宣纸，品质极佳',
  },
  {
    id: 'paper_011',
    categoryId: 'cat_017',
    batchNumber: 'BATCH-2024-011',
    curtainPatternSpacing: 1.55,
    fiberComposition: '桑皮',
    thickness: 0.08,
    colorL: 81,
    colorA: 4,
    colorB: 13,
    pHValue: 7.0,
    stockQuantity: 100,
    unit: '张',
    storageLocation: 'B-01-02',
    purchaseDate: '2024-05-10',
    supplier: '陕西长安皮纸厂',
    notes: '明代皮纸，适合书画古籍',
  },
  {
    id: 'paper_012',
    categoryId: 'cat_020',
    batchNumber: 'BATCH-2024-012',
    curtainPatternSpacing: 1.35,
    fiberComposition: '大麻',
    thickness: 0.1,
    colorL: 72,
    colorA: 5,
    colorB: 22,
    pHValue: 6.6,
    stockQuantity: 85,
    unit: '张',
    storageLocation: 'B-01-05',
    purchaseDate: '2024-05-25',
    supplier: '山西平遥麻纸厂',
    notes: '明代麻纸，非常稀有',
  },
  {
    id: 'paper_013',
    categoryId: 'cat_021',
    batchNumber: 'BATCH-2024-013',
    curtainPatternSpacing: 1.45,
    fiberComposition: '青檀皮、沙田稻草',
    thickness: 0.088,
    colorL: 84,
    colorA: 2,
    colorB: 12,
    pHValue: 7.2,
    stockQuantity: 95,
    unit: '张',
    storageLocation: 'B-02-01',
    purchaseDate: '2024-06-01',
    supplier: '安徽泾县宣纸厂',
    notes: '清代净皮宣纸，保存良好',
  },
  {
    id: 'paper_014',
    categoryId: 'cat_022',
    batchNumber: 'BATCH-2024-014',
    curtainPatternSpacing: 1.65,
    fiberComposition: '楮皮',
    thickness: 0.07,
    colorL: 77,
    colorA: 3,
    colorB: 17,
    pHValue: 6.8,
    stockQuantity: 130,
    unit: '张',
    storageLocation: 'B-02-02',
    purchaseDate: '2024-06-10',
    supplier: '浙江富阳皮纸厂',
    notes: '清代皮纸，适合普通修复',
  },
  {
    id: 'paper_015',
    categoryId: 'cat_023',
    batchNumber: 'BATCH-2024-015',
    curtainPatternSpacing: 2.1,
    fiberComposition: '竹纤维',
    thickness: 0.065,
    colorL: 74,
    colorA: 2,
    colorB: 21,
    pHValue: 6.4,
    stockQuantity: 170,
    unit: '张',
    storageLocation: 'B-02-03',
    purchaseDate: '2024-06-15',
    supplier: '福建连城竹纸厂',
    notes: '清代竹纸，帘纹粗犷',
  },
  {
    id: 'paper_016',
    categoryId: 'cat_024',
    batchNumber: 'BATCH-2024-016',
    curtainPatternSpacing: 1.1,
    fiberComposition: '棉纤维',
    thickness: 0.12,
    colorL: 90,
    colorA: 0,
    colorB: 5,
    pHValue: 7.6,
    stockQuantity: 200,
    unit: '张',
    storageLocation: 'B-02-04',
    purchaseDate: '2024-06-20',
    supplier: '上海棉纸厂',
    notes: '清代棉纸，质地厚实',
  },
  {
    id: 'paper_017',
    categoryId: 'cat_025',
    batchNumber: 'BATCH-2024-017',
    curtainPatternSpacing: 1.75,
    fiberComposition: '苎麻',
    thickness: 0.09,
    colorL: 70,
    colorA: 6,
    colorB: 24,
    pHValue: 6.5,
    stockQuantity: 75,
    unit: '张',
    storageLocation: 'B-02-05',
    purchaseDate: '2024-06-25',
    supplier: '湖南浏阳麻纸厂',
    notes: '清代麻纸，耐久性强',
  },
  {
    id: 'paper_018',
    categoryId: 'cat_026',
    batchNumber: 'BATCH-2024-018',
    curtainPatternSpacing: 1.28,
    fiberComposition: '青檀皮、沙田稻草',
    thickness: 0.082,
    colorL: 89,
    colorA: 1,
    colorB: 8,
    pHValue: 7.8,
    stockQuantity: 300,
    unit: '张',
    storageLocation: 'C-01-01',
    purchaseDate: '2024-07-01',
    supplier: '安徽泾县红星宣纸厂',
    notes: '现代工艺红星宣纸，品质稳定',
  },
  {
    id: 'paper_019',
    categoryId: 'cat_027',
    batchNumber: 'BATCH-2024-019',
    curtainPatternSpacing: 1.58,
    fiberComposition: '楮皮',
    thickness: 0.068,
    colorL: 83,
    colorA: 2,
    colorB: 14,
    pHValue: 7.4,
    stockQuantity: 250,
    unit: '张',
    storageLocation: 'C-01-02',
    purchaseDate: '2024-07-10',
    supplier: '浙江富阳皮纸厂',
    notes: '现代工艺皮纸，价格实惠',
  },
  {
    id: 'paper_020',
    categoryId: 'cat_028',
    batchNumber: 'BATCH-2024-020',
    curtainPatternSpacing: 1.95,
    fiberComposition: '竹纤维、木浆',
    thickness: 0.052,
    colorL: 80,
    colorA: 1,
    colorB: 16,
    pHValue: 7.0,
    stockQuantity: 500,
    unit: '张',
    storageLocation: 'C-01-03',
    purchaseDate: '2024-07-15',
    supplier: '广西南宁竹纸厂',
    notes: '现代竹纸，性价比高，适合练习',
  },
  {
    id: 'paper_021',
    categoryId: 'cat_029',
    batchNumber: 'BATCH-2024-021',
    curtainPatternSpacing: 1.15,
    fiberComposition: '棉纤维',
    thickness: 0.11,
    colorL: 92,
    colorA: 0,
    colorB: 4,
    pHValue: 8.0,
    stockQuantity: 400,
    unit: '张',
    storageLocation: 'C-01-04',
    purchaseDate: '2024-07-20',
    supplier: '江苏苏州棉纸厂',
    notes: '现代棉纸，洁白柔软',
  },
  {
    id: 'paper_022',
    categoryId: 'cat_030',
    batchNumber: 'BATCH-2024-022',
    curtainPatternSpacing: 1.85,
    fiberComposition: '苎麻、木浆',
    thickness: 0.085,
    colorL: 75,
    colorA: 4,
    colorB: 20,
    pHValue: 6.9,
    stockQuantity: 150,
    unit: '张',
    storageLocation: 'C-01-05',
    purchaseDate: '2024-07-25',
    supplier: '四川隆昌麻纸厂',
    notes: '现代麻纸，坚韧耐用',
  },
];

export const mockBooks: Book[] = [
  {
    id: 'book_001',
    name: '史记',
    dynasty: '宋',
    author: '司马迁',
    totalVolumes: 130,
    description: '二十四史之首，中国第一部纪传体通史，记载了上至上古传说中的黄帝时代，下至汉武帝太初四年间共3000多年的历史。此版本为南宋建安黄善夫刻本，具有极高的历史文献价值。',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'book_002',
    name: '本草纲目',
    dynasty: '明',
    author: '李时珍',
    totalVolumes: 52,
    description: '明代著名医学家李时珍撰写的一部具有世界性影响的博物学著作，全书共52卷，载有药物1892种，收集医方11096个，绘制精美插图1160幅。此版本为明万历年间金陵胡承龙刻本。',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'book_003',
    name: '全唐诗',
    dynasty: '清',
    author: '彭定求 等',
    totalVolumes: 900,
    description: '清代康熙年间编校的唐五代诗歌总集，共收录唐代诗人2873人，诗作49403首，共计900卷，是研究唐代文学的重要文献。此版本为清康熙四十六年扬州诗局刻本。',
    createdAt: '2024-02-01T00:00:00Z',
  },
];

function generatePolygon(centerX: number, centerY: number, size: number): Point[] {
  const points: Point[] = [];
  const sides = 4 + Math.floor(Math.random() * 3);
  for (let i = 0; i < sides; i++) {
    const angle = (i / sides) * Math.PI * 2 + Math.random() * 0.5;
    const radius = size * (0.7 + Math.random() * 0.6);
    points.push({
      x: centerX + Math.cos(angle) * radius,
      y: centerY + Math.sin(angle) * radius,
    });
  }
  return points;
}

export const mockPages: BookPage[] = [
  {
    id: 'page_001',
    bookId: 'book_001',
    volumeNumber: 1,
    pageNumber: 15,
    curtainPatternSpacing: 1.25,
    fiberComposition: '青檀皮、沙田稻草',
    thickness: 0.082,
    colorL: 78,
    colorA: 4,
    colorB: 16,
    pHValue: 6.2,
    frontImage: '/images/books/book001/v001/p015_front.jpg',
    backImage: '/images/books/book001/v001/p015_back.jpg',
    status: '待修复',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'page_002',
    bookId: 'book_001',
    volumeNumber: 1,
    pageNumber: 23,
    curtainPatternSpacing: 1.28,
    fiberComposition: '青檀皮、沙田稻草',
    thickness: 0.085,
    colorL: 76,
    colorA: 5,
    colorB: 18,
    pHValue: 6.0,
    frontImage: '/images/books/book001/v001/p023_front.jpg',
    backImage: '/images/books/book001/v001/p023_back.jpg',
    status: '修复中',
    createdAt: '2024-01-12T14:30:00Z',
  },
  {
    id: 'page_003',
    bookId: 'book_001',
    volumeNumber: 5,
    pageNumber: 42,
    curtainPatternSpacing: 1.22,
    fiberComposition: '青檀皮、沙田稻草',
    thickness: 0.080,
    colorL: 80,
    colorA: 3,
    colorB: 14,
    pHValue: 6.8,
    frontImage: '/images/books/book001/v005/p042_front.jpg',
    backImage: '/images/books/book001/v005/p042_back.jpg',
    status: '已修复',
    createdAt: '2024-01-08T09:00:00Z',
  },
  {
    id: 'page_004',
    bookId: 'book_002',
    volumeNumber: 3,
    pageNumber: 18,
    curtainPatternSpacing: 1.55,
    fiberComposition: '桑皮',
    thickness: 0.078,
    colorL: 74,
    colorA: 6,
    colorB: 20,
    pHValue: 5.8,
    frontImage: '/images/books/book002/v003/p018_front.jpg',
    backImage: '/images/books/book002/v003/p018_back.jpg',
    status: '待检测',
    createdAt: '2024-02-20T11:00:00Z',
  },
  {
    id: 'page_005',
    bookId: 'book_002',
    volumeNumber: 8,
    pageNumber: 56,
    curtainPatternSpacing: 1.58,
    fiberComposition: '桑皮',
    thickness: 0.082,
    colorL: 72,
    colorA: 7,
    colorB: 22,
    pHValue: 5.5,
    frontImage: '/images/books/book002/v008/p056_front.jpg',
    backImage: '/images/books/book002/v008/p056_back.jpg',
    status: '已检测',
    createdAt: '2024-02-25T15:45:00Z',
  },
  {
    id: 'page_006',
    bookId: 'book_003',
    volumeNumber: 12,
    pageNumber: 34,
    curtainPatternSpacing: 1.42,
    fiberComposition: '竹纤维',
    thickness: 0.065,
    colorL: 70,
    colorA: 4,
    colorB: 24,
    pHValue: 5.2,
    frontImage: '/images/books/book003/v012/p034_front.jpg',
    backImage: '/images/books/book003/v012/p034_back.jpg',
    status: '待修复',
    createdAt: '2024-03-10T10:30:00Z',
  },
  {
    id: 'page_007',
    bookId: 'book_003',
    volumeNumber: 25,
    pageNumber: 67,
    curtainPatternSpacing: 1.45,
    fiberComposition: '竹纤维',
    thickness: 0.068,
    colorL: 73,
    colorA: 3,
    colorB: 21,
    pHValue: 5.6,
    frontImage: '/images/books/book003/v025/p067_front.jpg',
    backImage: '/images/books/book003/v025/p067_back.jpg',
    status: '已修复',
    createdAt: '2024-03-15T13:20:00Z',
  },
  {
    id: 'page_008',
    bookId: 'book_003',
    volumeNumber: 50,
    pageNumber: 89,
    curtainPatternSpacing: 1.38,
    fiberComposition: '竹纤维',
    thickness: 0.062,
    colorL: 68,
    colorA: 5,
    colorB: 26,
    pHValue: 5.0,
    frontImage: '/images/books/book003/v050/p089_front.jpg',
    backImage: '/images/books/book003/v050/p089_back.jpg',
    status: '待修复',
    createdAt: '2024-03-20T09:15:00Z',
  },
];

export const mockDamageAreas: DamageArea[] = [
  {
    id: 'damage_001',
    pageId: 'page_001',
    type: '虫蛀',
    polygonPoints: generatePolygon(200, 300, 15),
    area: 7.07,
    lapWidth: 3,
    twistDirection: '顺时针',
    patchPaperId: null,
    notes: '蠹鱼蛀蚀，呈不规则圆形孔洞',
  },
  {
    id: 'damage_002',
    pageId: 'page_001',
    type: '虫蛀',
    polygonPoints: generatePolygon(450, 250, 20),
    area: 12.57,
    lapWidth: 4,
    twistDirection: '逆时针',
    patchPaperId: 'paper_004',
    notes: '多个蛀洞连片，面积较大',
  },
  {
    id: 'damage_003',
    pageId: 'page_002',
    type: '撕裂',
    polygonPoints: [
      { x: 100, y: 400 },
      { x: 150, y: 420 },
      { x: 250, y: 450 },
      { x: 200, y: 470 },
      { x: 100, y: 440 },
    ],
    area: 22.5,
    lapWidth: 5,
    twistDirection: '顺时针',
    patchPaperId: 'paper_013',
    notes: '书口处撕裂，长度约15厘米',
  },
  {
    id: 'damage_004',
    pageId: 'page_002',
    type: '霉蚀',
    polygonPoints: generatePolygon(500, 500, 30),
    area: 28.27,
    lapWidth: 5,
    twistDirection: '逆时针',
    patchPaperId: null,
    notes: '水渍导致霉变，纸质严重受损',
  },
  {
    id: 'damage_005',
    pageId: 'page_004',
    type: '缺角',
    polygonPoints: [
      { x: 0, y: 0 },
      { x: 80, y: 0 },
      { x: 80, y: 100 },
      { x: 0, y: 120 },
    ],
    area: 88,
    lapWidth: 6,
    twistDirection: '顺时针',
    patchPaperId: null,
    notes: '左上角缺失，约占页面八分之一',
  },
  {
    id: 'damage_006',
    pageId: 'page_005',
    type: '酸化',
    polygonPoints: generatePolygon(300, 400, 40),
    area: 50.27,
    lapWidth: 4,
    twistDirection: '逆时针',
    patchPaperId: 'paper_010',
    notes: '严重酸化，纸张酥脆易碎',
  },
  {
    id: 'damage_007',
    pageId: 'page_006',
    type: '虫蛀',
    polygonPoints: generatePolygon(250, 350, 12),
    area: 4.52,
    lapWidth: 2,
    twistDirection: '顺时针',
    patchPaperId: null,
    notes: '小型蛀洞，数量较多',
  },
  {
    id: 'damage_008',
    pageId: 'page_006',
    type: '折痕',
    polygonPoints: [
      { x: 50, y: 300 },
      { x: 600, y: 290 },
      { x: 600, y: 310 },
      { x: 50, y: 320 },
    ],
    area: 16.5,
    lapWidth: 3,
    twistDirection: '顺时针',
    patchPaperId: 'paper_019',
    notes: '对折痕导致纤维断裂',
  },
  {
    id: 'damage_009',
    pageId: 'page_008',
    type: '磨损',
    polygonPoints: generatePolygon(400, 550, 25),
    area: 19.63,
    lapWidth: 4,
    twistDirection: '逆时针',
    patchPaperId: null,
    notes: '书角磨损严重，边缘残缺',
  },
  {
    id: 'damage_010',
    pageId: 'page_008',
    type: '水渍',
    polygonPoints: generatePolygon(150, 200, 35),
    area: 38.48,
    lapWidth: 5,
    twistDirection: '顺时针',
    patchPaperId: 'paper_020',
    notes: '大面积水渍污染，颜色发黄',
  },
];

export const mockRestorationRecords: RestorationRecord[] = [
  {
    id: 'record_001',
    pageId: 'page_003',
    paperId: 'paper_001',
    restorationDate: '2024-02-15',
    restorer: '张修复师',
    paperUsed: 1,
    beforeImage: '/images/restoration/record001_before.jpg',
    afterImage: '/images/restoration/record001_after.jpg',
    flatnessScore: 92,
    warpingRisk: '低',
    collapseRisk: '低',
    notes: '虫蛀修复，使用唐代风格宣纸，效果良好',
    createdAt: '2024-02-15T16:00:00Z',
  },
  {
    id: 'record_002',
    pageId: 'page_007',
    paperId: 'paper_020',
    restorationDate: '2024-04-10',
    restorer: '李修复师',
    paperUsed: 2,
    beforeImage: '/images/restoration/record002_before.jpg',
    afterImage: '/images/restoration/record002_after.jpg',
    flatnessScore: 85,
    warpingRisk: '中',
    collapseRisk: '低',
    notes: '竹纸修复，纤维略有差异，需压平处理',
    createdAt: '2024-04-10T14:30:00Z',
  },
  {
    id: 'record_003',
    pageId: 'page_002',
    paperId: 'paper_013',
    restorationDate: '2024-05-20',
    restorer: '王修复师',
    paperUsed: 1,
    beforeImage: '/images/restoration/record003_before.jpg',
    afterImage: '/images/restoration/record003_after.jpg',
    flatnessScore: 88,
    warpingRisk: '低',
    collapseRisk: '中',
    notes: '撕裂口修复，搭口处理细致',
    createdAt: '2024-05-20T11:00:00Z',
  },
  {
    id: 'record_004',
    pageId: 'page_005',
    paperId: 'paper_010',
    restorationDate: '2024-06-05',
    restorer: '张修复师',
    paperUsed: 3,
    beforeImage: '/images/restoration/record004_before.jpg',
    afterImage: '/images/restoration/record004_after.jpg',
    flatnessScore: 78,
    warpingRisk: '高',
    collapseRisk: '中',
    notes: '严重酸化修复，先进行脱酸处理，再补配',
    createdAt: '2024-06-05T15:45:00Z',
  },
  {
    id: 'record_005',
    pageId: 'page_006',
    paperId: 'paper_019',
    restorationDate: '2024-06-25',
    restorer: '陈修复师',
    paperUsed: 1,
    beforeImage: '/images/restoration/record005_before.jpg',
    afterImage: '/images/restoration/record005_after.jpg',
    flatnessScore: 90,
    warpingRisk: '低',
    collapseRisk: '低',
    notes: '折痕修复，使用现代竹纸，效果良好',
    createdAt: '2024-06-25T10:20:00Z',
  },
];

export const mockFiberOptions = fiberCompositions;

export const mockDynastyOptions = [...dynasties];

export const mockPaperTypeOptions = [...paperTypes];

export function getAllMockData() {
  return {
    books: mockBooks,
    pages: mockPages,
    damageAreas: mockDamageAreas,
    paperCategories: mockPaperCategories,
    paperStock: mockPaperStock,
    restorationRecords: mockRestorationRecords,
  };
}

export default getAllMockData;
